- Extra Long Factorials.java
Hey there,
Added the Extra Long Factorials problem from Hackerrank in Java.
> Added the Extra Long Factorials problem from Hackerrank

- Tkinter_Age_Calculator.py
> Tkinter_Age_Calculator.py

- leetcode/EditDistance.cpp
Edit Distance--Leetcode Question No 72.Based on Dynamic Programming.
>  EditDistance.cpp file added 

- leetcode/Median_of_two_sorted_array.c
added median of two sorted array program in c with proper comments
> Added median of two sorted array program

- KMP Algorithm.cpp
> Mukund's commit

- simplecalculator.py
Code for a simple calculator in python.
> Created simplecalculator.py

- Count BTN using C
Calculate blank,Tab and New Lines in C
> Create Count BTN using C

- Input Per Line
> Create Input Per Line

- Tabs and backspace
> Create Tabs and backspace

- Input to Output
> Create Input to Output

- Prime Less than Given No
Display Prime numbers less than given Input Number
> Create Prime Less than Given No

- digital-clock.html
a clock made using html css and javascript
> digital clock

- leetcode/1.Two_Sum.cpp
Added the Solution for Two Sum of Leetcode questions.
The code runs properly and has been checked on leetcode website.
Kindly merge my PR😊
Thank you!
> Added Two Sum Solution of Leetcode question

- Contribution of C program for Hacktober fest/First Problems
I have contributed here the solution of Minesweeper problem and Tic-Tac-Toe problem .Please merge it sir. If you find any issues then I am ready to edit the file just let me know. Thank you.
> Create First Problems

- leetcode/Valid _Stack_Sequences.cpp
Please accept this as hacktoberfest-accepted label.
> Valid Stack Sequences.cpp

- find roots of eqation.cpp
find the roots of any quadratic equation.
> find the roots.c

- binarysearchtree.c
Binary search tree operations implemented with Linked List.
> binary search tree with LL

- BMI_Calculator.c
Added a BMI Calculator C program 
Hactoberfest 2021 Contribution :-)
calculating the user’s BMI ((weight
multiplied by 703), divided by (height times height)). If the BMI is 30 or
greater, the script should write, “Your weight is considered to be unhealthy.”
Otherwise, if the BMI is 25 or greater, then write, “You are currently
considered to be overweight.” Otherwise, if the BMI is 18.5 or over, then write
“Your weight is considered normal and healthy”. Otherwise, write, “You are
considered underweight".
issue #19  solved
> BMI Calculator C Program

- Monkey Door Puzzle-Asked in Amazon Interviews.cpp
C++ Code Monkey Door Puzzle-Asked in Amazon Interviews
> Create Monkey Door Puzzle-Asked in Amazon Interviews.cpp

- Priority_Queue.cpp
Hello, this is my first time creating a pr. So if there is any mistake please let me know.
This is a code for Priority queue including priority sort, it is menu driven and takes the element and a specified priority (both integers) as input.
> Priority queue to be commited

- fibonacci.cpp
Pls merge !
Happy hacktoberfest!
Thanks
> Added Fibonacci code in c++

- README.md
- gameof31.cpp
31" is a card game played by 2 or more people
players. Generally each player's goal is to collect a number from
playing cards whose sum is as close as possible to 31. If
the sum of one player is greater than 31 then he automatically exits
toy ("burned"). The winner is the player with the highest total that is
less than or equal to 31.
> Add house of 31 Game in C++ 

- pallindrome_identifier.cpp
1) This is a program that takes a number as input from the user and checks whether the given number is a pallindrome or not.
2) This is my first time in open source and in hacktoberfest , so please merge it and add hacktoberfest-accepted label/tag to it.
3) If you want any changes or modification in it please say it to me and I will do those changes or modification.
> Added pallindrome identifier program

- xor_times_2_is_sum.cpp
solved the CodeChef problem with URL="https://www.codechef.com/problems/XORXORSUM".
please accept his pull request.
> add xor_times_2_is_sum.cpp

- mergesort4way.cpp
> 4 way merged sort
